### PR TITLE
AMRNAV-5933: add supporting of node composition

### PR DESCRIPTION
**Pull request by papertowel123**
Here is the ticket [AMRNAV-5933](https://lvserv01.logivations.com/browse/AMRNAV-5933), [PR](https://github.com/logivations/deep_cv/pull/7109) to deep_cv
On the left I start the component container, and on the right I load the `robot_localization::ekf` component
image

### CODE REVIEW

**Comment by maksymdidukh** [comment]
Here is the ticket [AMRNAV-5933](https://lvserv01.logivations.com/browse/AMRNAV-5933), PR to deep_cv [link]()
On the left I start the component container, and on the right I load the `robot_localization::ekf component`
image

**Review by HovorunB — APPROVED** [review]
Looks good!

**Comment by papertowel123** [comment]
I'll merge this PR and [AMRNAV-5933 deep_cv part](https://github.com/logivations/deep_cv/pull/7109) at the same time

**Review by andriimaistruk — APPROVED** [review]

**Comment by HovorunB** [comment]
> I'll merge this PR and [AMRNAV-5933 deep_cv part](https://github.com/logivations/deep_cv/pull/7109) at the same time

I think you have to merge it before the deep_cv PR so that the system tests pass

**Pull request merged**
